-- ============================================
-- 1. Create product_market_prices Table
-- ============================================
CREATE TABLE IF NOT EXISTS public.product_market_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Change from UUID to serial BIGINT
    product_name TEXT NOT NULL UNIQUE, -- Unique per product to allow Upsert
    category TEXT,
    price NUMERIC(12, 2) DEFAULT 0,
    unit TEXT DEFAULT 'kg', -- Default unit is 'kg'
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- 2. Realtime and Security
-- ============================================
-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE product_market_prices;

-- Enable RLS
ALTER TABLE product_market_prices ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for all"
ON product_market_prices FOR SELECT
TO authenticated, anon
USING (true);

CREATE POLICY "Enable insert/update for service role and admin"
ON product_market_prices FOR INSERT
TO service_role, authenticated
WITH CHECK (true);

CREATE POLICY "Enable update for service role and admin"
ON product_market_prices FOR UPDATE
TO service_role, authenticated
USING (true);

-- ============================================
-- 3. Initial Sample Data (Optional)
-- ============================================
/*
INSERT INTO product_market_prices (product_name, category, price, unit)
VALUES 
    ('Cabai Merah', 'Sayur', 45000, 'kg'),
    ('Telur Bebek', 'Protein', 3500, 'butir'),
    ('Melon Golden', 'Buah', 25000, 'kg')
ON CONFLICT (product_name) DO NOTHING;
*/
