-- =============================================
-- SOP Farmer RAG Tables (Per Company)
-- Purpose: Store SOPs with embeddings for AI/RAG matching
-- Integration: n8n WhatsApp bot uses these to guide farmers
-- =============================================

-- =============================================
-- LYORI (Hidroponik / Farm Oils)
-- =============================================
CREATE TABLE IF NOT EXISTS public.sop_farmer_lyori (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  content TEXT NULL,
  embedding public.vector NULL,
  metadata JSONB NULL,
  CONSTRAINT sop_farmer_lyori_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Match function for RAG
CREATE OR REPLACE FUNCTION match_sop_farmer_lyori(
  query_embedding vector(768),
  match_threshold float DEFAULT 0.5,
  match_count int DEFAULT 5
)
RETURNS TABLE (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    sop.id,
    sop.content,
    sop.metadata,
    1 - (sop.embedding <=> query_embedding) as similarity
  FROM sop_farmer_lyori sop
  WHERE 1 - (sop.embedding <=> query_embedding) > match_threshold
  ORDER BY sop.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- =============================================
-- MOAFARM (Pertanian Umum)
-- =============================================
CREATE TABLE IF NOT EXISTS public.sop_farmer_moafarm (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  content TEXT NULL,
  embedding public.vector NULL,
  metadata JSONB NULL,
  CONSTRAINT sop_farmer_moafarm_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Match function for RAG
CREATE OR REPLACE FUNCTION match_sop_farmer_moafarm(
  query_embedding vector(768),
  match_threshold float DEFAULT 0.5,
  match_count int DEFAULT 5
)
RETURNS TABLE (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    sop.id,
    sop.content,
    sop.metadata,
    1 - (sop.embedding <=> query_embedding) as similarity
  FROM sop_farmer_moafarm sop
  WHERE 1 - (sop.embedding <=> query_embedding) > match_threshold
  ORDER BY sop.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- =============================================
-- KAJA
-- =============================================
CREATE TABLE IF NOT EXISTS public.sop_farmer_kaja (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  content TEXT NULL,
  embedding public.vector NULL,
  metadata JSONB NULL,
  CONSTRAINT sop_farmer_kaja_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Match function for RAG
CREATE OR REPLACE FUNCTION match_sop_farmer_kaja(
  query_embedding vector(768),
  match_threshold float DEFAULT 0.5,
  match_count int DEFAULT 5
)
RETURNS TABLE (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    sop.id,
    sop.content,
    sop.metadata,
    1 - (sop.embedding <=> query_embedding) as similarity
  FROM sop_farmer_kaja sop
  WHERE 1 - (sop.embedding <=> query_embedding) > match_threshold
  ORDER BY sop.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- =============================================
-- SAMPLE DATA (Placeholder - akan diisi via n8n/embeddings)
-- Metadata example: {"category": "Pemeliharaan", "title": "Pengukuran PPM", "version": "1.0"}
-- =============================================

-- Lyori placeholder
INSERT INTO sop_farmer_lyori (content, metadata) VALUES
('Langkah pengukuran PPM nutrisi harian: 1. Kalibrasi TDS Meter sebelum pengukuran. 2. Celupkan probe ke dalam larutan nutrisi. 3. Tunggu hingga angka stabil. 4. Range optimal: 1200-1400 PPM untuk fase generatif. Jika PPM kurang dari 1000, tambahkan nutrisi A+B. Jika PPM lebih dari 1500, encerkan dengan air bersih.', 
 '{"category": "Pemeliharaan", "title": "Pengukuran PPM Nutrisi", "version": "1.0"}'),
('Pengecekan pH air: 1. Kalibrasi pH meter dengan buffer 7.0. 2. Ukur pH larutan. 3. Range optimal: 5.5-6.5. Jika pH kurang dari 5.5, tambahkan pH Up. Jika pH lebih dari 6.5, tambahkan pH Down.',
 '{"category": "Pemeliharaan", "title": "Pengecekan pH Air", "version": "1.0"}'),
('Prosedur panen hidroponik: 1. Pastikan sayuran telah mencapai ukuran standar. 2. Warna harus cerah dan segar. 3. Potong dengan gunting bersih. 4. Masukkan ke wadah bersih. 5. Simpan di suhu 4-8 derajat Celsius.',
 '{"category": "Panen", "title": "Panen Produk Hidroponik", "version": "1.0"}');

-- Moafarm placeholder
INSERT INTO sop_farmer_moafarm (content, metadata) VALUES
('Jadwal pemupukan tanaman: Pupuk dasar diberikan saat tanam. Pupuk susulan setiap 2 minggu. Dosis NPK 200kg/ha, Urea 100kg/ha. Cara aplikasi: Buat lingkaran 15cm dari batang, taburkan pupuk merata, tutup dengan tanah tipis, siram segera setelah pemupukan.',
 '{"category": "Pemeliharaan", "title": "Pemupukan Tanaman", "version": "1.0"}'),
('Waktu penyiraman optimal: Pagi 06.00-08.00, Sore 16.00-18.00. Volume tanaman muda 0.5L/tanaman, tanaman dewasa 1-2L/tanaman. Indikator kebutuhan air: tanah kering 3cm dari permukaan berarti perlu disiram.',
 '{"category": "Pemeliharaan", "title": "Penyiraman Tanaman", "version": "1.0"}'),
('Monitoring hama harian: 1. Periksa daun bagian bawah. 2. Cek batang dan pangkal tanaman. 3. Catat jenis hama yang ditemukan. Tindakan: Hama ringan semprot pestisida organik, hama berat lapor ke supervisor.',
 '{"category": "Perlindungan", "title": "Pengendalian Hama", "version": "1.0"}');

-- Kaja placeholder
INSERT INTO sop_farmer_kaja (content, metadata) VALUES
('Prosedur kerja harian: Jam masuk 07.00, istirahat 12.00-13.00, pulang 16.00. Checklist harian: Absen kehadiran, cek peralatan kerja, laporkan kondisi lapangan, dokumentasi progress.',
 '{"category": "Operasional", "title": "Prosedur Kerja Harian", "version": "1.0"}'),
('Kategori kendala: Ringan (bisa ditangani sendiri), Sedang (perlu bantuan rekan), Berat (perlu keputusan supervisor). Cara melapor: Foto kondisi masalah, kirim via WhatsApp ke supervisor, tunggu instruksi sebelum bertindak.',
 '{"category": "Operasional", "title": "Pelaporan Kendala", "version": "1.0"}'),
('APD wajib digunakan: Sepatu boots, sarung tangan, topi atau helm. Larangan: Bekerja saat hujan petir, menggunakan alat rusak, bekerja sendiri di area berbahaya.',
 '{"category": "K3", "title": "Keselamatan Kerja", "version": "1.0"}');

-- =============================================
-- Note: Embeddings perlu di-generate via n8n atau API
-- Gunakan node "Supabase Vector Store" di n8n untuk insert dengan embedding
-- =============================================
