-- 1. Create Invoices Table
create table if not exists public.invoices (
    id bigint generated by default as identity primary key, -- Auto-increment 1, 2, 3...
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    summary_text text,
    whatsapp_raw text, -- Original message backup
    customer_phone text,
    pdf_url text, -- This is the ONLY field n8n leaves empty (Web fills this)
    status text default 'pending', -- pending, processing, ready, sent
    company_id uuid -- Optional, keeps reference to valid company UUIDs
);

-- 2. Enable Realtime for this table
alter publication supabase_realtime add table invoices;

-- 3. Storage Bucket Setup (Run this via Dashboard or generic SQL if supported)
-- Note: Creating buckets via SQL is specific to Supabase Storage API extensions, 
-- usually better done in Dashboard > Storage > Create Bucket 'invoices'.
-- 
-- Recommended Policy for 'invoices':
-- SELECT: Public (or Authenticated)
-- INSERT: Authenticated (Service Role / Users)
-- UPDATE: Authenticated

-- 4. RLS Policies (Optional but recommended)
alter table invoices enable row level security;

create policy "Enable read access for authenticated users"
on invoices for select
to authenticated
using (true);

create policy "Enable insert for authenticated users and service role"
on invoices for insert
to authenticated, service_role
with check (true);

create policy "Enable update for authenticated users"
on invoices for update
to authenticated
using (true);
