<template>
  <div class="company-detail animate-fade-in-up">
    <div v-if="loading" class="flex flex-col items-center justify-center p-2xl h-64 text-muted">
      <div class="spinner-premium mb-md"></div>
      <span class="animate-pulse">Mengakses database perusahaan...</span>
    </div>

    <template v-else-if="company">
      <!-- Company Header Hero -->
      <div class="premium-card mb-xl overflow-hidden relative">
        <div class="card-bg-glow"></div>
        <div class="p-xl flex justify-between items-center relative z-10">
          <div class="flex items-center gap-lg">
            <div class="icon-pod-large" :class="getCompanyColorClass(company.code)">
              <AppIcon :name="getCompanyIconName(company.code)" :size="32" />
            </div>
            <div>
              <h2 class="text-3xl font-bold text-main mb-xs">{{ company.name }}</h2>
              <div class="flex items-center gap-sm">
                <span class="font-mono text-sm text-muted bg-white/5 px-2 py-1 rounded">
                  {{ company.code }}
                </span>
                <span class="status-badge" :class="company.is_active ? 'active' : 'inactive'">
                  {{ company.is_active ? 'Operasional' : 'Non-Aktif' }}
                </span>
              </div>
            </div>
          </div>
          
          <div class="flex gap-md">
             <!-- Future Actions -->
          </div>
        </div>
      </div>

      <!-- AI Profile Summary -->
      <div v-if="aiSummary || aiLoading" class="premium-card ai-card mb-2xl">
        <div class="p-lg border-b border-glass flex justify-between items-center bg-glass-accent">
          <div class="flex items-center gap-md">
            <div class="ai-orb-pulse"></div>
            <div>
              <h3 class="font-bold text-lg text-main">Intelijen Bisnis & Analisis Operasional</h3>
              <p class="text-xs text-muted">Generated by Cortex AI • Real-time Insights</p>
            </div>
          </div>
          <div class="flex gap-sm">
            <button 
              v-if="canModify && getSubmissionUrl()" 
              @click="openUploadForm" 
              class="btn-ghost-sm" 
              title="Upload Dokumen Baru"
            >
                <AppIcon name="upload-cloud" :size="18" />
                <span class="hidden md:inline ml-xs">Upload Data</span>
            </button>
            <button 
              @click="refreshAISummary" 
              class="btn-ghost-sm" 
              title="Refresh Analisis"
              :disabled="aiLoading"
            >
                <AppIcon name="refresh-cw" :size="18" :class="{ 'animate-spin': aiLoading }" />
            </button>
          </div>
        </div>
        
        <div class="p-xl min-h-[200px]">
          <div v-if="aiLoading" class="flex flex-col items-center justify-center py-xl">
              <div class="spinner-sm mb-md text-emerald-500"></div> 
              <span class="text-muted text-sm italic">Menganalisa dokumen dan struktur aset...</span>
          </div>
          <div v-else class="markdown-body-premium" v-html="renderMarkdown(aiSummary)"></div>
        </div>
      </div>

      <!-- Stats Grid -->
      <div class="stats-grid mb-2xl">
        <div class="premium-card stat-card hover-lift">
          <div class="stat-icon-box emerald">
            <AppIcon name="file-text" :size="20" />
          </div>
          <div>
            <span class="text-xs font-bold text-muted uppercase tracking-wider">Total Laporan</span>
            <div class="text-2xl font-bold text-main tabular-nums">{{ stats.total }}</div>
          </div>
        </div>

        <div class="premium-card stat-card hover-lift">
          <div class="stat-icon-box blue">
            <AppIcon name="calendar" :size="20" />
          </div>
          <div>
            <span class="text-xs font-bold text-muted uppercase tracking-wider">Laporan Hari Ini</span>
            <div class="text-2xl font-bold text-main tabular-nums">{{ stats.today }}</div>
          </div>
        </div>

        <div class="premium-card stat-card hover-lift">
          <div class="stat-icon-box purple">
            <AppIcon name="trending-up" :size="20" />
          </div>
          <div>
            <span class="text-xs font-bold text-muted uppercase tracking-wider">Minggu Ini</span>
            <div class="text-2xl font-bold text-main tabular-nums">{{ stats.week }}</div>
          </div>
        </div>
        
        <div class="premium-card stat-card hover-lift">
            <div class="stat-icon-box amber">
              <AppIcon name="eye" :size="20" />
            </div>
            <div>
              <span class="text-xs font-bold text-muted uppercase tracking-wider">View Count</span>
              <div class="text-2xl font-bold text-main tabular-nums">{{ reports.length }}</div>
            </div>
          </div>
      </div>

      <!-- Reports Table -->
      <div class="premium-card overflow-hidden">
        <div class="p-lg border-b border-glass flex justify-between items-center">
          <h3 class="font-bold text-lg flex items-center gap-md">
            <AppIcon name="clipboard" :size="20" class="text-muted" />
            Laporan Harian
          </h3>
          <!-- Filters could follow here -->
        </div>
        
        <div v-if="reports.length === 0" class="flex flex-col items-center justify-center p-3xl text-muted">
          <div class="w-16 h-16 bg-white/5 rounded-full flex items-center justify-center mb-md">
            <AppIcon name="inbox" :size="32" opacity="0.5" />
          </div>
          <p>Belum ada data laporan yang tersedia.</p>
        </div>
        
        <div v-else class="table-responsive">
          <table class="elite-table">
            <thead>
              <tr>
                <th>Waktu Lapor</th>
                <th>Operator</th>
                <th>Aktivitas Utama</th>
                <th>Status Kendala</th>
                <th>Cuaca</th>
                <th>Catatan Tambahan</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="report in reports" :key="report.id" class="hover-row">
                <td class="font-mono text-sm whitespace-nowrap font-medium text-main">
                  {{ formatDate(report.report_date) }}
                </td>
                <td class="text-sm">{{ report.user_id || '-' }}</td>
                <td class="max-w-[200px]">
                  <div class="truncate text-sm" :title="getActivitiesSummary(report.activities)">
                    {{ getActivitiesSummary(report.activities) }}
                  </div>
                </td>
                <td>
                  <span v-if="hasIssues(report.issues)" class="issue-badge warning">
                    <AppIcon name="alert-circle" :size="12" />
                    Ada Masalah
                  </span>
                  <span v-else class="issue-badge success">
                    <AppIcon name="check-circle" :size="12" />
                    Aman
                  </span>
                </td>
                <td>
                  <span class="weather-tag">
                    {{ report.weather || '-' }}
                  </span>
                </td>
                <td class="text-sm text-muted italic max-w-xs truncate">
                  {{ truncate(report.notes, 40) || '-' }}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </template>

    <div v-else class="flex flex-col items-center justify-center h-[60vh] text-center">
      <div class="text-8xl mb-lg opacity-20">🏢</div>
      <h2 class="text-2xl font-bold text-main mb-sm">Perusahaan Tidak Ditemukan</h2>
      <p class="text-muted mb-xl">Data perusahaan yang Anda cari tidak tersedia di sistem.</p>
      <router-link to="/" class="btn-primary-new">Kembali ke Dashboard</router-link>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, computed, watch } from 'vue'
import { useRoute } from 'vue-router'
import { supabase, COMPANY_TABLES, VIEWS } from '@/services/supabase'
import { aiService } from '@/services/ai'
import { useAuthStore } from '@/stores/auth'
import AppIcon from '@/components/AppIcon.vue'

const route = useRoute()
const authStore = useAuthStore()

// State
const loading = ref(true)
const aiLoading = ref(false)
const company = ref(null)
const reports = ref([])
const generalDocs = ref([])
const aiSummary = ref('')
const stats = ref({ total: 0, today: 0, week: 0 })

const companyId = computed(() => route.params.id)
const canModify = computed(() => authStore.user && (authStore.isAdmin || authStore.isOwner))

const getCompanyIconName = (code) => {
  const iconMap = {
    'Lyori': 'layers',
    'moafarm': 'sprout',
    'Kaja': 'feather', // Assuming feather icon implies bird/duck
    'EP': 'layout',
    'ePanen': 'layout',
    'ML': 'circle',
    'Melon': 'circle',
    'Owner': 'briefcase'
  }
  return iconMap[code] || 'briefcase'
}

const getCompanyColorClass = (code) => {
    // Just a helper to return theme colors based on company
    if (code === 'Lyori') return 'orange'
    if (code === 'moafarm') return 'emerald'
    return 'blue'
}

const formatDate = (dateStr) => {
  if (!dateStr) return '-'
  return new Date(dateStr).toLocaleDateString('id-ID', {
    day: 'numeric',
    month: 'short',
    year: 'numeric'
  })
}

const truncate = (text, length) => {
  if (!text) return ''
  return text.length > length ? text.substring(0, length) + '...' : text
}

const getActivitiesSummary = (activities) => {
  if (!activities) return '-'
  if (typeof activities === 'string') return truncate(activities, 50)
  if (activities.summary) return truncate(activities.summary, 50)
  return '-'
}

const hasIssues = (issues) => {
  if (!issues) return false
  if (Array.isArray(issues)) return issues.length > 0
  if (typeof issues === 'object') return Object.keys(issues).length > 0
  return false
}

const renderMarkdown = (text) => {
  if (!text) return ''
  let html = text
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      .replace(/^(#+) (.*$)/gm, (match, level, content) => {
          const size = Math.min(6, level.length + 2)
          return `<h${size} class="md-heading">${content}</h${size}>`
      })
      .replace(/\n\n/g, '<br><br>')
      .replace(/\n/g, '<br>')
      .replace(/- \[(.*?)\]/g, '• $1')
      .replace(/- (.*$)/gm, '• $1')
  
  return html
}

const getTableConfig = () => {
  for (const [name, config] of Object.entries(COMPANY_TABLES)) {
    if (config.id === companyId.value) {
      return { name, ...config }
    }
  }
  return null
}

const loadAISummary = async (companyData, force = false) => {
    aiLoading.value = true
    try {
        const { data: docs } = await supabase
          .from(VIEWS.ALL_GENERAL_DOCS)
          .select('*')
          .ilike('company_name', `%${companyData.name}%`)
          .limit(100)
        
        generalDocs.value = docs || []
        
        aiSummary.value = await aiService.summarizeCompanyProfile(
            generalDocs.value, 
            companyData.id, 
            companyData.name,
            force
        )
    } catch (err) {
        console.error('AI Summary failed:', err)
    } finally {
        aiLoading.value = false
    }
}

const refreshAISummary = () => {
    if (company.value) {
        loadAISummary(company.value, true)
    }
}

const loadCompanyData = async () => {
  loading.value = true
  aiSummary.value = '' 
  
  try {
    const { data: companyData, error: companyError } = await supabase
      .from('companies')
      .select('*')
      .eq('id', companyId.value)
      .single()
    
    if (companyError) throw companyError
    company.value = companyData

    const tableConfig = getTableConfig()
    if (tableConfig) {
        try {
            const { data: reportsData, error: reportsErr } = await supabase
              .from(tableConfig.dailyReports)
              .select('*')
              .order('report_date', { ascending: false })
              .limit(50)
            
            if (!reportsErr) {
                reports.value = reportsData || []
            }
            
            const today = new Date().toISOString().split('T')[0]
            const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
            
            try {
                // Simplified counters for demo purposes if exact count fails
                const { count: total } = await supabase.from(tableConfig.dailyReports).select('*', { count: 'exact', head: true })
                const { count: todayCount } = await supabase.from(tableConfig.dailyReports).select('*', { count: 'exact', head: true }).eq('report_date', today)
                const { count: weekCount } = await supabase.from(tableConfig.dailyReports).select('*', { count: 'exact', head: true }).gte('report_date', weekAgo)
                
                stats.value = { total: total || 0, today: todayCount || 0, week: weekCount || 0 }
            } catch (statErr) {
                console.warn('Stat fetching failed', statErr)
            }
        } catch (tableErr) {
            console.error('Unexpected reports table error:', tableErr)
        }
    }
  } catch (err) {
    console.error('Failed to load company data:', err)
  } finally {
    loading.value = false
  }

  if (company.value) {
      loadAISummary(company.value)
  }
}

const DOC_FORMS = {
    'Lyori': 'https://n8n-wrw2bveswawm.cica.sumopod.my.id/form/72b3dbbe-34c7-48f0-b7de-f2e7c017d519',
    'moafarm': 'https://n8n-wrw2bveswawm.cica.sumopod.my.id/form/4a20bcf8-ed90-4910-9451-45631fc26fe5',
    'Kaja': 'https://n8n-wrw2bveswawm.cica.sumopod.my.id/form/ea756b54-6155-4de3-be2a-415bb3cd769e'
}

const getSubmissionUrl = () => {
    if (!company.value) return null
    const name = company.value.name
    if (name.includes('Lyori')) return DOC_FORMS['Lyori']
    if (name.toLowerCase().includes('moafarm')) return DOC_FORMS['moafarm']
    if (name.includes('Kaja')) return DOC_FORMS['Kaja']
    return null
}

const openUploadForm = () => {
    const url = getSubmissionUrl()
    if (url) window.open(url, '_blank')
}

watch(companyId, () => {
  loadCompanyData()
})

onMounted(() => {
  loadCompanyData()
})
</script>

<style scoped>
/* Icon Pods */
.icon-pod-large {
    width: 64px;
    height: 64px;
    border-radius: 20px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    box-shadow: 0 10px 25px -5px currentColor;
}
.icon-pod-large.emerald { background: linear-gradient(135deg, #10b981, #059669); color: rgba(16, 185, 129, 0.4); }
.icon-pod-large.emerald svg { color: white; }
.icon-pod-large.orange { background: linear-gradient(135deg, #f97316, #c2410c); color: rgba(249, 115, 22, 0.4); }
.icon-pod-large.orange svg { color: white; }
.icon-pod-large.blue { background: linear-gradient(135deg, #3b82f6, #1d4ed8); color: rgba(59, 130, 246, 0.4); }
.icon-pod-large.blue svg { color: white; }

.status-badge {
    padding: 2px 8px;
    border-radius: 100px;
    font-size: 0.7rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.05em;
}
.status-badge.active { background: rgba(16, 185, 129, 0.1); color: #10b981; border: 1px solid rgba(16, 185, 129, 0.2); }
.status-badge.inactive { background: rgba(239, 68, 68, 0.1); color: #ef4444; border: 1px solid rgba(239, 68, 68, 0.2); }

/* AI Card */
.ai-card {
    border: 1px solid rgba(16, 185, 129, 0.2);
    box-shadow: 0 0 20px rgba(16, 185, 129, 0.05);
}

.ai-orb-pulse {
    width: 12px;
    height: 12px;
    border-radius: 50%;
    background: #10b981;
    box-shadow: 0 0 10px #10b981;
    animation: pulse-green 2s infinite;
}

@keyframes pulse-green {
    0% { transform: scale(0.95); opacity: 0.7; }
    50% { transform: scale(1.1); opacity: 1; }
    100% { transform: scale(0.95); opacity: 0.7; }
}

.btn-ghost-sm {
    padding: 6px 12px;
    border-radius: 8px;
    color: var(--text-muted);
    font-size: 0.85rem;
    font-weight: 600;
    transition: all 0.2s;
    border: 1px solid transparent;
}
.btn-ghost-sm:hover {
    background: rgba(var(--text-main-rgb), 0.05);
    color: var(--color-primary);
    border-color: rgba(var(--text-main-rgb), 0.1);
}

/* Stats */
.stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: var(--space-lg);
}

.stat-card {
    display: flex;
    align-items: center;
    gap: var(--space-md);
    padding: var(--space-lg);
}

.stat-icon-box {
    width: 48px;
    height: 48px;
    border-radius: 14px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
}
.stat-icon-box.emerald { background: linear-gradient(135deg, #10b981, #059669); }
.stat-icon-box.blue { background: linear-gradient(135deg, #3b82f6, #1d4ed8); }
.stat-icon-box.purple { background: linear-gradient(135deg, #8b5cf6, #6d28d9); }
.stat-icon-box.amber { background: linear-gradient(135deg, #f59e0b, #d97706); }

/* Table */
.elite-table {
    width: 100%;
    border-collapse: collapse;
}
.elite-table th {
    text-align: left;
    padding: 16px 24px;
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--text-muted);
    border-bottom: 1px solid var(--glass-border);
    background: rgba(var(--text-main-rgb), 0.02);
}
.elite-table td {
    padding: 16px 24px;
    border-bottom: 1px solid var(--glass-border);
    color: var(--text-main);
    vertical-align: top;
}
.hover-row:hover td {
    background: rgba(var(--text-main-rgb), 0.02);
}

.issue-badge {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 4px 10px;
    border-radius: 8px;
    font-size: 0.75rem;
    font-weight: 700;
}
.issue-badge.warning { background: rgba(239, 68, 68, 0.1); color: #ef4444; }
.issue-badge.success { background: rgba(16, 185, 129, 0.1); color: #10b981; }

.weather-tag {
    background: rgba(59, 130, 246, 0.1);
    color: #3b82f6;
    padding: 2px 8px;
    border-radius: 6px;
    font-size: 0.8rem;
    font-weight: 600;
}

/* Markdown Styling specific for AI */
:deep(.markdown-body-premium) {
    color: var(--text-main);
    line-height: 1.7;
    font-size: 0.95rem;
}
:deep(.markdown-body-premium strong) {
    color: var(--color-primary);
    font-weight: 700;
}
:deep(.markdown-body-premium h3) {
    font-size: 1.1rem;
    font-weight: 800;
    margin-top: 1.5em;
    margin-bottom: 0.5em;
    color: var(--text-main);
    border-left: 3px solid var(--color-primary);
    padding-left: 12px;
}
</style>
